# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: '0 0 * * *' }]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master
  push: { branches: ['master'] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master

        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          debug: true
          template: classic
          config_gemoji: yes # use additional non-unicode emoji
          config_octicon: yes # use github octicons
          retries: 5
          retries_delay: 300
          retries_output_action: 5
          retries_delay_output_action: 300
          use_prebuilt_image: yes # faster execution

          # base
          # base: header, activity, metadata
          base_indepth: yes
          repositories_forks: yes
          repositories_affiliations: ''
          commits_authoring: Niaro, George Kayzer, George Evstigneev, niaronir@gmail.com, george@bridgerpay.com, ge@pro.rent, niaro@users.noreply.github.com

          # The languages plugin displays which programming languages you use the most across all your repositories.
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 0
          plugin_languages_recent_days: 365
          plugin_languages_recent_load: 1000
          # plugin_languages_ignored: html, css, javascript               # List of languages to ignore
          # plugin_languages_skipped: my-test-repo                       # List of repositories to skip
          # plugin_languages_colors: "0:orange, javascript:#ff0000, ..." # Make most used languages orange and JavaScript red
          plugin_languages_details: bytes-size, percentage, lines # Additionally display total bytes size and percentage
          plugin_languages_threshold: 2% # Hides all languages less than 2%

          # The lines of code plugin displays the number of lines of code you have added and removed across all of your repositories.
          plugin_lines: yes
          plugin_lines_history_limit: 10

          plugin_achievements: yes
          # plugin_achievements_threshold: X

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_reactions: yes
          plugin_reactions_details: percentage, count
          plugin_reactions_limit: 1000

          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_followup_indepth: yes
          plugin_followup_archived: yes
